### ISSUE TITLE
Delete tree photos after upload

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/TreeTracker#17]
Add a "Delete Tree Photos?" option once the upload queue has been completed, to help keep space down as our projects get bigger. We've had 2,000 tree photos in a day, and maybe 5 projects back to back, so if the app can tidy up after itself that avoids less technical users having to figure out how to delete all those photos (and not other photos)

Manually clearing out photos can be tricky, especially when they're scattered throughout other photos, perhaps I photo the area, or a cute farm dog, or the volunteers, and want to only delete the tree photos not the other useful photos.

**Comment by allanlang** [comment]
Initial implementation had a flaw that could lead to photos being deleted where the user had declined to do so. Reopening for a fix.

**Comment by philsturgeon** [comment]
This works really well, thank you so much!! It kept all the scenery photos I took and all the tube photos are gone. I love it.

**Comment by allanlang** [comment]
Thanks so much for the feedback @philsturgeon. I'll get this released for Supervisors now.
