### ISSUE TITLE
Automate iOS Builds

### ISSUE THREAD

**Issue by philsturgeon** [protect-earth/TreeTracker#43]
With GitHub Actions could we automate the release of iOS builds to TestFlight/App Store, so that we don't have to pester @sunshinejr to build them?

I spotted this:
https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6

I also saw a semantic-release based solution floating around a while back, which could help give appropriate version numbers based on feature or fix.

**Comment by allanlang** [comment]
No. It’s all set up on my fork and needs pulling into the main repo, so still some work to be done here. I’ll get a PR together.
