### ISSUE TITLE
Location accuracy

### ISSUE THREAD

**Issue by hansallis** [protect-earth/TreeTracker#44]
While looking over the code, I noticed that it seems that the accuracy of the location's not taken into consideration. With my current understanding of the use of the application, this seems like a risk that may need to be mitigated. At the very least, the user could be made aware of the issue. Woud like to hear your thoughts.

**Comment by hansallis** [comment]
I've added a warning message over the camera view. It disappears automatically as soon as the GPS gets more accurate. Not preventing photo taking for now, because this already took me way too long to implement. I'm not that familiar with Swift nor UIKit, so this might not follow the usual approach or might even leak memory. It does appear to work reliably, which is easy to test by enabling and disabling precise location information under privacy settings.

**Comment by philsturgeon** [comment]
Lot's of stragglers showing up at the latest event. 

<img width="451" alt="Screen Shot 2021-11-22 at 4 42 02 PM" src="https://user-images.githubusercontent.com/67381/142900870-deb8defc-e925-4de1-aa3e-c9b4510455c2.png">
