### ISSUE TITLE
Add Rollbar instrumentation to help with troubleshooting in the field

### ISSUE THREAD

**Issue by allanlang** [protect-earth/TreeTracker#62]
As an iOS app developer
I need to receive notifications, including contextual information if possible, of errors occurring in the app when in use in the field
in order to troubleshoot issues effectively and identify any fixes that may be required

**Comment by philsturgeon** [comment]
I've made a new rollbar account and got the API running on it. I also made a project, invited you, and started looking at how to get iOS on it.

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/67381/177382633-c73d0308-b75f-495e-b717-3c3941aefc73.png">

Hopefully those instructions for iOS will make it fairly easy.
