### ISSUE TITLE
Adapt data layer to new Laravel backend

### ISSUE THREAD

**Issue by allanlang** [protect-earth/TreeTracker#63]
Sub-tasks:

- [x] Remove unused `treesPlanted` function from API protocol and implementations
- [x] Create new Supervisor service (ideally async style) to establish pattern for pulling from new Api (i.e. auth, object mapping etc.)
- [x] Create new Site service based on Supervisor service
- [x] Create new Species service
- [ ] Adapt tree upload to new backend
- [ ] Add "add site" functionality to Site service

**Comment by allanlang** [comment]
Waiting on https://github.com/protect-earth/protect-earth-api/issues/60

**Comment by philsturgeon** [comment]
Update on blockers: https://github.com/protect-earth/protect-earth-api/issues/92 is done and https://github.com/protect-earth/protect-earth-api/issues/60 is just being used as a place to track feedback on the new upload endpoint, as the mock PR has been merged already.

**Comment by allanlang** [comment]
Waiting on https://github.com/protect-earth/protect-earth-api/issues/121
