### ISSUE TITLE
Disable "add site" functionality when using Nova API

### ISSUE THREAD

**Issue by allanlang** [protect-earth/TreeTracker#75]
The add site functionality is no longer required in the iOS app and is not supported by the new Nova API, so this functionality should be neatly disabled but ideally be fairly simple to bring back to life in future if desired.

**Comment by philsturgeon** [comment]
It can just be killed with fire, along with all the Airtable logic. I dont want to complicate matters by trying to keep things around but hidden behind toggles, we need to just trim the fat here I think. I'll be carrying around an iPad at all times in case I need to get into the Nova backend so iPhone worries are less.

**Comment by allanlang** [comment]
@philsturgeon I've prepared the linked PR to remove add site and all of the redundant Airtable code. This is the quite the clear-out, and will yield 0.10.3 which I suggest we focus our testing efforts on for the time being.
