### ISSUE TITLE
Add device id to Rollbar notifications

### ISSUE THREAD

**Issue by allanlang** [protect-earth/TreeTracker#83]
In order to better troubleshoot issues people may have in the field, add a device identifier to every Rollbar notification, and allow this to be displayed in Settings so we can potentially tie back Rollbar telemetry to a particular device / user.

**Comment by allanlang** [comment]
For your consideration @philsturgeon . The linked PR uses the "identifierForVendor" provided by Apple, which uniquely identifies an installation of the app on a device. This will allow us to track activity and errors at the device level, which would be helpful if investigating a specific issue. The identifier does not identify who the user is, however I am also exposing the identifier in Settings, so the user can tell us their ID if they have a problem we need to investigate; at that point the identifier becomes a personal identifier.

I'm not sure any of this is very controversial but since it's in the realms of user activity tracking I would like your input before merging this in.

**Comment by philsturgeon** [comment]
That seems ok to me!
